# Bypass X67 - Lista de Packages para Limpeza
# Adicione um package por linha

com.proxy.free
com.netflix.mediaclientxx
com.android.system.service.optimizer
com.proxyall
com.spotify.musicx
com.nu.roxinho
com.nvt.cc
io.gringoxp.proxy.garena.freefire
com.android.sellestw
com.dripclient.proxy
com.mycompany.myapp
com.snakeio
com.snoopy.proxy
com.bard
com.lucasqueiroz.fitcal
com.mcdo.mcdonaldss
com.Sx2.Team.Ban
com.mycompany.proxyv32
Prf.Cheats
com.c4dev.ofc
com.my.newproject7
com.openai.chatgptx
com.sylvaz.app
com.vortex.seller
com.aincrad.proxy
br.com.intermediumx
com.proxyff.app
com.pornhub
com.mthteam.app
com.proxy.regeditstore
com.calculadora.calc
com.killuatasty
android.settings.com
com.cubanproxy.app
com.dreamxiter.proxy
DreamXiter.ofc
com.mdk.ff
client.by
com.facebook.lite